name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Setup Zig
        uses: jassielof/setup-zig@v1

      - name: Formatting
        run: zig fmt --check build.zig build.zig.zon cmd

      - name: Build
        run: zig build --summary all

      - name: Tests
        run: zig build tests --summary all
